api_url = TELEUP_API_URL
api_key = TELEUP_API_KEY

ftp_server = BILLING_FTP_SERVER
ftp_user = BILLING_FTP_USERNAME
ftp_pass = BILLING_FTP_PASSWORD

affiliate_name = BILLING_AFFILIATE_NAME
system = BILLING_SYSTEM_IDENTIFIER

healthcheck_url = HEALTHCHECK_URL
